Version 0.0.2
FuenRob/gomv pull request #4
Opened 2024-11-08 00:50 UTC by JuanPerdomo00

La versión 0.0.2 se agregaron las siguientes

- Add: [6f5f8bc](https://github.com/JuanPerdomo00/gomv/commit/6f5f8bc25ac835842859513a599e98d9d014b899) LICENSE MIT
- Add: [aaadd6](https://github.com/JuanPerdomo00/gomv/commit/aaadd6cc1fe4c98561856bd2c489d8b1867740b8) Package colors lib
- Add: [a9a10a](https://github.com/JuanPerdomo00/gomv/commit/a9a10a3f3eac1d046d3511d2b3372fa8fec464ff) Update version, y se agregaron mejoras en la stdout de `help` tambien se agrego el comando `config` ya que no permitia crear la carpeta cuando se ejecutaba por primera vez. Fix
- Add: [d6e802](https://github.com/JuanPerdomo00/gomv/commit/d6e802bfa9afec81f4f4782a06f0afb2f8c6b097) Package Color mod
- Update: [41d1a4](https://github.com/JuanPerdomo00/gomv/commit/41d1a4bf763c581185c3219eb7469ee9caa779e2) Se agrego el `-o govm` para que el binario se compile con ese nombre, tambien se agrego el funcionamiento de el comando `config`

2024-11-08 17:53 UTC, FuenRob requested changes

2024-11-08 17:53 UTC, FuenRob commented on main.go
> +		colors.SetColor(32, "Usage: govm <command> [version] or <help> to more info\n")
¿Por qué en algunos sitios usamos color.Fg**** y aquí el 32? Entiendo que es porque se usa la función el paquete govm/colors, pero no entiendo por qué cambia.

2024-11-08 17:53 UTC, FuenRob commented on main.go
> +	"github.com/fatih/color"
Si tenemos el modulo **govm/color**, tal vez lo ideas sea importar este paquete solo en ese fichero y que todas las asignaciones de color se hagan con funciones en el paquete **govm/color**. De este modo evitamos importar el paquete **github.com/fatih/color** en dos sitios.

2024-11-08 18:06 UTC, JuanPerdomo00 commented on main.go
> +		colors.SetColor(32, "Usage: govm <command> [version] or <help> to more info\n")
Olvide cambiarlo mala mia, creía que se vería  mejor con los números, pero el paquete color ya me da esas constantes que tienen el entero referente al color, se ve mas estético y ordenado si se usa con `Fgcolor`

2024-11-08 18:10 UTC, JuanPerdomo00 commented on main.go
> +	"github.com/fatih/color"
Lo que pasa y es lo del comentario anterior, es por la estética al llamar las constantes `Fgcolor` que tienen como valor el número referente al color que tiene como nombre la constante, si no queremos importar, entonces toca dejarlos como números y guiarnos en los comentarios del package color.

2024-11-10 11:45 UTC, FuenRob approved these changes

2024-11-10 11:45 UTC, merged